#数据库相关配置
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/zeagle?characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto = none
spring.thymeleaf.check-template=false
spring.thymeleaf.check-template-location=false
spring.jpa.open-in-view=false
mybatis.mapper-locations=classpath:dao/*.xml